# Generated by Django 3.0.4 on 2020-10-19 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(choices=[('ゲーム', 'ゲーム'), ('プログラミング', 'プログラミング'), ('麻雀', '麻雀'), ('映画', '映画'), ('その他の雑談', 'その他の雑談'), ('一発ネタ', '一発ネタ')])),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('name', models.CharField(max_length=160)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('num', models.IntegerField()),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Thread')),
            ],
        ),
    ]
